baseURL = "https://sea257.github.io/myblog/"
relativeURLs = false
canonifyURLs = true
title   = "Sigberts Shack"
theme   = "PaperMod"
paginate = 0

publishDir = "docs"

[params] 
	customCSS = ["css/custom.css"]

