name: Build and deploy Hugo site

# Grant GITHUB_TOKEN the rights to push to GitHub Pages:
permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Hugo Extended
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "latest"
          extended: true

      - name: Build site with Hugo
        run: |
          hugo --minify \
            --destination docs \
            --baseURL "https://sea257.github.io/myblog/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          # Tells the action where our generated files live:
          publish_dir: ./docs
          # Use the built-in GITHUB_TOKEN:
          github_token: ${{ secrets.GITHUB_TOKEN }}
