cat << 'EOF' > .github/workflows/gh-pages.yml
name: Build and deploy Hugo site

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "latest"
          extended: true

      - name: Generate site
        run: |
          hugo --minify \
               --destination docs

      - name: Commit built files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: rebuild site via GitHub Actions"
          file_pattern: docs/**
EOF
